### ISSUE TITLE
Error when "Thresholds missing"

### ISSUE THREAD

**Issue by rk125** [Sineos/node-red-contrib-hysteresis#4]
Hello Sineos!

If threshold type is dynamic, and something is changed in code causing node redeployment, node shows "Thresholds missing" after deployment and does not output anything when next current value is received. After setting threshold all is fine of course. 
Could it be possible to add some error message so it can be caught in the code in next node?
Thanks for the node!
Reggie

**Comment by Sineos** [comment]
Thanks for the report.

Would it be a solution to add a `msg.payload` "Thresholds missing" in such case? Then it could be handled in subsequent nodes

**Comment by rk125** [comment]
I would say why not, then I could check is with isNaN. If it is good practice :) I'm not really JS guy.

**Comment by Sineos** [comment]
I mean basically you could go the other way round:
- If you work with dyn thresholds, it is known that they are lost on deploy
- Solution: Build a logic to make sure that the threshold is injected automatically after deploy, e.g. Inject Node with "inject once"

To be honest, this would be cleaner than "polluting" the flow with some additional messages in my opinion.

**Comment by rk125** [comment]
Yes, that would work with full deploy. I discovered "Deploy modified flows" comes pretty handy, but it does not kick in "inject once" process on inject node for example.
May be 2nd output with error messages then?

**Comment by Sineos** [comment]
FWIW, I did some tests:
- Full deploy will clear the hysteresis settings but also kicks "inject once"
- Partial deploy will not clear the settings and also does not kick "inject once"

Nevertheless, there might be other constructs that need to make sure that we have the thresholds set, so I came up with following:
![error](https://user-images.githubusercontent.com/4459312/97102299-9084c500-16a4-11eb-88dc-174fadc45774.gif)

In addition to raising an error, I also added a node's context that will save:
![grafik](https://user-images.githubusercontent.com/4459312/97102352-f07b6b80-16a4-11eb-906f-0fbefcf6fa66.png)

This will allow the node to "recover" their previous values IF you use a persistent context storage, e.g. file, as default

**Comment by rk125** [comment]
Perfect Sineos! Exactly what was needed!

**Comment by Sineos** [comment]
New version is published. Please test

**Comment by rk125** [comment]
Works like charm for me! Thank you!
